name: Railway_DSS
description: Complete AI Railway DSS UI with all modules and mock data
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=2.18.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  charts_flutter: ^0.12.0
  google_fonts: ^6.2.1 
  fl_chart: ^0.69.0
  url_launcher: ^6.1.11
dev_dependencies:
  flutter_test:
    sdk: flutter
  google_maps_flutter: ^2.5.0
  flutter_map: ^6.0.0
  latlong2: ^0.9.0
flutter:
  uses-material-design: true
  
  # This is the section where you will add your image assets.
  assets:
    - assets/indian_railways_logo.jpeg
    - assets/indian_railways_bg.jpg
    - assets/indian_railways_bg2.jpg
    - assets/indian_railways_bg3.jpg
    - assets/indian_railways_bg4.jpg
    - assets/indian_railways_bg5.jpg
    - assets/title_page_img.png
    - assets/train_loco.jpg
    - assets/chennai_central.jpg
    - assets/Bengaluru.jpg
    - assets/sanghamitra.jpg
    - assets/mumbai.jpg
    - assets/yercaud.jpg
    - assets/Mysuru.jpg
    - assets/RailOPT-AI.png
    - assets/indian_railways_front.jpg